export const CidadaoSmartAgendamentoDataHoraPageSelectors = {
  route: /\/agendamentos\/novo\/data-e-hora/,
  tituloDataHora: /data e hora/i,
  cardRequerente: /requerente/i,
  campoNome: /nome/i,
  campoDataNascimento: /data de nascimento/i,
  campoEmail: /e-mail|email/i,
  campoCpf: /cpf/i,
  campoTelefone: /telefone celular|telefone/i,
  placeholderSelecione: /selecione/i,
  tituloModalHorario: /horario de atendimento|horário de atendimento/i,
  botaoConfirmar: /confirmar/i,
  botaoProsseguir: /prosseguir/i,
  mensagemNomeSobrenome: /digite nome e sobrenome/i,
  mensagemTelefoneObrigatorio: /telefone.*obrigatorio|telefone.*obrigatório|campo obrigatorio|campo obrigatório/i,
  mensagemDataInvalida: /data invalida|data inválida/i,
  mensagemMenorIdade: /menor de 16|idade minima|minima de 16|mínima de 16/i,
};
